# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-03-30 12:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('car_photo', models.ImageField(blank=True, null=True, upload_to='image_upload/driver/car_photo')),
                ('car_model', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('location_lat', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('location_lon', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('name', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('birthday', models.DateField(blank=True, null=True)),
                ('own_photo', models.ImageField(blank=True, null=True, upload_to='image_upload/driver/own_photo')),
            ],
            options={
                'verbose_name': 'Driver',
            },
        ),
    ]
