# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-03-30 12:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boober', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('name', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('birthday', models.DateField(blank=True, null=True)),
                ('own_photo', models.ImageField(blank=True, null=True, upload_to='image_upload/client/own_photo')),
                ('location_lat', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('location_lon', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('boobs_size', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Client',
            },
        ),
    ]
