# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-03-30 12:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boober', '0003_ride'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proposal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('distance', models.IntegerField(blank=True, null=True)),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='my_proposals', to='boober.Driver')),
            ],
            options={
                'verbose_name': 'Proposal',
            },
        ),
        migrations.AddField(
            model_name='ride',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='boober.Client'),
        ),
        migrations.AddField(
            model_name='proposal',
            name='ride',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='proposals', to='boober.Ride'),
        ),
        migrations.AddField(
            model_name='ride',
            name='selected_proposal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='boober.Proposal'),
        ),
    ]
