# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-03-30 15:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boober', '0005_auto_20180330_1022'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='boober.Driver'),
        ),
        migrations.AddField(
            model_name='ride',
            name='proposed_drivers',
            field=models.ManyToManyField(blank=True, related_name='_ride_proposed_drivers_+', to='boober.Driver'),
        ),
    ]
