# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-03-30 20:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boober', '0006_auto_20180330_1054'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ride',
            name='proposed_drivers',
        ),
    ]
