# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-03-30 21:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boober', '0007_auto_20180330_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='age',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='boobs_size',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='own_photo',
            field=models.ImageField(null=True, upload_to='image_upload/client/own_photo', verbose_name='Selfie'),
        ),
    ]
