# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-03-30 21:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boober', '0008_auto_20180330_1616'),
    ]

    operations = [
        migrations.CreateModel(
            name='RideCancelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('reason', models.TextField(blank=True, default='', null=True)),
                ('ride', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cancelation', to='boober.Ride')),
            ],
            options={
                'verbose_name': 'Ride cancelation',
            },
        ),
    ]
