# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-03-30 23:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boober', '0010_ridecancelation'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProposalAccept',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('proposal', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='accept', to='boober.Proposal')),
            ],
            options={
                'verbose_name': 'Proposal accept',
            },
        ),
        migrations.AlterField(
            model_name='ride',
            name='status',
            field=models.CharField(blank=True, choices=[('waiting_proposals', 'waiting_proposals'), ('ride', 'ride'), ('canceled', 'canceled'), ('done', 'done')], default='', max_length=17, null=True),
        ),
    ]
