# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-03-30 21:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boober', '0010_ridecancelation'),
        ('boober', '0007_remove_ride_proposed_drivers'),
    ]

    operations = [
    ]
