# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-03-30 23:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boober', '0011_auto_20180330_1802'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposalaccept',
            name='consent',
            field=models.BooleanField(default=False, verbose_name='I confirm I am at least 18 years old, and I will need to show naked boobs to the driver after the ride.'),
        ),
    ]
