# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-03-30 23:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boober', '0012_proposalaccept_consent'),
        ('boober', '0011_merge_20180330_1651'),
    ]

    operations = [
    ]
