# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-03-31 00:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boober', '0014_auto_20180330_1907'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ridefeedback',
            old_name='status',
            new_name='paid',
        ),
    ]
