# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-03-31 05:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boober', '0016_proposal_accepted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ridefinish',
            name='ride',
        ),
        migrations.RemoveField(
            model_name='driver',
            name='birthday',
        ),
        migrations.AddField(
            model_name='client',
            name='phone',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='driver',
            name='age',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='driver',
            name='phone',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='proposal',
            name='comment',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='driver',
            name='car_model',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='driver',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='driver',
            name='own_photo',
            field=models.ImageField(blank=True, null=True, upload_to='image_upload/driver/own_photo', verbose_name='Selfie'),
        ),
        migrations.DeleteModel(
            name='RideFinish',
        ),
    ]
