# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-03-31 08:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boober', '0019_auto_20180331_0332'),
    ]

    operations = [
        migrations.CreateModel(
            name='DriverProposalCancel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('proposal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='proposal_status', to='boober.Proposal')),
            ],
            options={
                'verbose_name': 'Driver proposal cancel',
            },
        ),
    ]
